version: "3"
services:
    broker:
        container_name: streamr_dev_broker
        image: streamr/broker
        restart: on-failure
        depends_on:
            - init_keyspace
        links:
            - cassandra
            - kafka
            - redis
    data-api:
        container_name: streamr_dev_data-api
        image: streamr/data-api
        restart: on-failure
        ports:
            - "8890:8890"
        depends_on:
            - init_keyspace
        links:
            - cassandra
            - kafka
            - redis
            - zookeeper
        environment:
            STREAMR_URL: http://10.200.10.1:8081/streamr-core
    engine-and-editor:
        container_name: streamr_dev_engine-and-editor
        image: streamr/engine-and-editor:marketplace
        ports:
            - "8081:8081"
        depends_on:
            - init_keyspace
        links:
            - mysql
            - cassandra
            - kafka
            - redis
            - zookeeper
            - broker
            - data-api
        entrypoint: "grails"
        command: "-Dstreamr.database.host=mysql -Dstreamr.kafka.bootstrap.servers=kafka:9092 -Dstreamr.redis.hosts=redis -Dstreamr.cassandra.hosts=cassandra test run-app"

